# manager节点的host地址
MANAGER_HOST=127.0.0.1


# manager的端口号
MANAGER_PORT=8090

# executor的端口号
EXECUTOR_PORT=8092

# gateway的端口号
GATEWAY_PORT=8091


# 数据库类型:mysql或postgres
DB_TYPE=mysql

# mysql的host地址
MYSQLDB_HOST=192.168.31.57
# mysql的端口号
MYSQLDB_PORT=3306
# mysql的库名
MYSQLDB_NAME=sqlrest
# mysql的账号
MYSQLDB_USERNAME=root
# mysql的密码
MYSQLDB_PASSWORD=123456

# pgsql的host地址
PGDB_HOST=192.168.31.57
# pgsql的端口号
PGDB_PORT=5432
# pgsql的库名
PGDB_NAME=sqlrest
# pgsql的账号
PGDB_USERNAME=postgres
# pgsql的密码
PGDB_PASSWORD=123456

# JSON序列化时区设置
JSON_TIMEZONE=Asia/Shanghai

# 外部配置化网关/管理地址，默认注释，如果需要自行打开
#SQLREST_MANAGER_URL=http://localhost:8090
#SQLREST_GATEWAY_URL=http://localhost:8091