FROM openjdk:8-jre-alpine

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ADD sqlrest-release.tar.gz  /

EXPOSE      9088

USER        root

WORKDIR /sqlrest-release

RUN chmod u+x /sqlrest-release/bin/startup.sh

CMD  ["/sqlrest-release/bin/startup.sh","gateway"]

