server:
  port: ${EXECUTOR_PORT}
spring:
  application:
    name: sqlrest-executor
  main:
    allow-bean-definition-overriding: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQLDB_HOST}:${MYSQLDB_PORT}/${MYSQLDB_NAME}?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false&allowMultiQueries=true&failOverReadOnly=false&connectTimeout=30000&serverTimezone=Asia/Shanghai
    username: ${MYSQLDB_USERNAME}
    password: ${MYSQLDB_PASSWORD}
    validation-query: SELECT 1
    test-on-borrow: true

sqlrest:
  cache:
    hazelcast:
      enabled: true
    redis:
      enabled: false
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 0

mybatis:
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:logback-executor.xml

eureka:
  instance:
    prefer-ip-address: true
    secure-port-enabled: false
    non-secure-port-enabled: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${MANAGER_HOST}:${MANAGER_PORT}/eureka/

datasource:
  driver:
    base-path: ${APP_DRIVERS_PATH}